First draft of introduction-to-smart-contracts.rst
solidity-docs/tr-turkish pull request #13
Opened 2022-06-28 14:10 UTC by AliErcanOzgokce

line: 35 default (needs opinion) n.o.
line: 40 behave!= davranmak yerine behave==farklı sonuçlar verebileceği
line: 44 collection (do you have any alternatives for this word?)
line: 46-47 (needs opinion) n.o.
line: 48 contract ❌
line: 50 n.o.
line: 51 n.o.
line: 111-112 n.o.
line: 134-135 n.o.
line: 139-140 n.o.
line: 155-157 n.o.
line: 174-178 n.o.
line: 208-210 n.o.
line: 552-556 n.o.

2022-06-29 08:25 UTC, kuzdogan reviewed
Ufak şeyler önerdim eline sağlık :+1:

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Bir sonraki satır, kaynak kodun Solidity 0.4.16 sürümü veya 0.9.0 sürümüne
Tam ifade olmamış gibi. "0.4.16'dan başlayarak 0.9.0'a kadar (0.9.0 hariç) olan sürümler için yazıldığını..."

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +        // Event'ler müşterilerin sözleşme üzerinde yaptığınız
client=istemci

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +    function balances(address account) external view returns (uint) {
alt çizgiyi neden sildin burada?

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Web uygulamaları gibi Ethereum istemcileri, blockchainde yayılan (emit) bu olaylardan (event) fazla maliyet olmadan veri alabilir.
blokzincir'de veya blok zincir'de. Bunu tutarlı bi şekilde kullansak güzel olur. Hangisi doğru bilmiyorum ayrı veya birleşik, tutarlı olmamız yeterli.

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +``msg`` değişkeni (``tx`` ve ``block`` ile birlikte), blockchain'e erişim izini veren özellikleri olan :ref:`özel bir global değişken <special-variables-functions>`dir.
blokzincir

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +sözde bir işlem oluşturmanız gerekir.
*sözde* Türkçe'de gerçekte var olmayan gibi oluyor. Sözde değil de tırnak içinde "işlem" desek o ifadeyi sağlar gibi

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Her hesabın, 256-bit sözcükleri **storage** adı verilen 256-bit sözcüklere e
satır atlamış

2022-06-29 08:25 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +.. index:: ! selfdestruct, deactivate
"!" yanlışlıkla mı burada

2022-06-29 08:30 UTC, kuzdogan commented
Terimler için birkaç kaynak buldum bunlara bakabiliriz.Hepsini birebir almamız gerektiği anlamına gelmiyor ama uygun ve karşılığı sağladığını düşündüğümüz kelimeleri alabiliriz.

README'ye de koyabiliriz bunları:
- [Türk Standartları Enstitüsü Bilişim Sözlüğü](https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf)
- [Türkiye Bilişim Derneği Bilişim Sözlüğü](https://eski.tbd.org.tr/index.php?sayfa=sozluk&mi1&tipi=tren&harf=A)
- http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm

2022-06-29 09:13 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +olduğunu söyler. Kaynak kodu yayınlamanın varsayılan olduğu bir ortamda
default çevirisi varsayılan ama anlam olarak standart diyebiliriz

2022-06-29 09:13 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Solidity kapsamında olan bir sözleşme, Ethereum blockchain ağında belirli bir adreste bulunan kod (*fonksiyonlar*) ve veri (*durum*) koleksiyonudur.
koleksiyon yerine "bütünüdür" denebilir. Koleksiyon da ok gibi

2022-06-29 09:13 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Mappingler, her olası anahtarın başlangıçtan itibaren var olduğu ve bayt temsilinin tamamı sıfır
İkiye bölelim cümleyi:

Mapping'ler, sanal bir şekilde tanımlanıp değer atanan `hash tabloları <https://en.wikipedia.org/wiki/Hash_table>`_
olarak görülebilir. Bu yapıda mümkün olan her anahtar değeri tanımlandığı andan itibaren bulunur ve bu anahtarların eşlendiği değer (byte gösterminde) sıfırdır.

2022-06-29 09:13 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +satırında yayınlanan (emit) bir :ref:`”olay (event)" <events>` bildirir.
yayınlanan (publish) değil de yayılan

2022-06-29 16:26 UTC, AliErcanOzgokce commented on docs/introduction-to-smart-contracts.rst
> +Bir sonraki satır, kaynak kodun Solidity 0.4.16 sürümü veya 0.9.0 sürümüne
Tamamdır 👍.

2022-06-29 16:26 UTC, AliErcanOzgokce commented on docs/introduction-to-smart-contracts.rst
> +        // Event'ler müşterilerin sözleşme üzerinde yaptığınız
Tamamdır 👍.

2022-06-29 16:27 UTC, AliErcanOzgokce commented on docs/introduction-to-smart-contracts.rst
> +    function balances(address account) external view returns (uint) {
Gözden kaçmış olmalı, hemen düzeltiyorum.

2022-06-29 16:28 UTC, AliErcanOzgokce commented on docs/introduction-to-smart-contracts.rst
> +Web uygulamaları gibi Ethereum istemcileri, blockchainde yayılan (emit) bu olaylardan (event) fazla maliyet olmadan veri alabilir.
blok zincir kullanmamız sanki daha mantıklı olucak, çeviriyi güncelleyip kavram dizinine ekliyeceğim.

2022-06-29 16:28 UTC, AliErcanOzgokce commented on docs/introduction-to-smart-contracts.rst
> +``msg`` değişkeni (``tx`` ve ``block`` ile birlikte), blockchain'e erişim izini veren özellikleri olan :ref:`özel bir global değişken <special-variables-functions>`dir.
👍

2022-07-01 08:00 UTC, kuzdogan requested changes
Sadece ~~yayınlamak~~ yayılmaz atlanmış bir yerde onun dışında :+1:

2022-07-01 08:00 UTC, kuzdogan commented on docs/introduction-to-smart-contracts.rst
> +Event yayınlanır yayınlanmaz, veri alıcısı ``from``, ``to`` ve ``amount`` argümanlarını alır,
yayılır yayılmaz

2022-07-01 08:07 UTC, merged