Installing solidity.rst
solidity-docs/tr-turkish pull request #19
Opened 2022-07-05 18:12 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #10 
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 80
- satır: 101-104
- satır: 213-214 (lenient)
- satır: 317 (dependecies)
- satır: 512-513
- satır: 538

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- Branch = Kol, Dal
- Repository = Depo
- Image = İmaj (Docker için)
- Interface = Arayüz
- Formula = Formula (Homebrew'e Özel Bir Kavram)
- Symlinks = Kısayol Bağlantısı
- Components = Bileşen
- Fork = Çatallamak
- Breaking Changes = İşleyişi Bozan Değişiklikler/ Kırılan Değişiklikler
- Nightly Development Builds = Gecelik Geliştirme Yapıları/Derlemeleri

## Ek Açıklamalar (Opsiyonel)
Remote' a yönelik bir çeviri önerisine ihtiyacım var. Ayrıca 178. satır son sürüm olarak yanlış bir şey belirtmiş gibi ana repoya bunun hakkında issue açmak gerekir mi?

## Kontrol Listesi
- [ ] Çeviri için son kontrolleri yaptım.
- [ ] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-07-06 16:41 UTC, kuzdogan requested changes

2022-07-06 16:41 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Yayınlanan en son sürüm için ``stable`` etiketini ve geliştirme kolundaki (branch) potansiyel olarak kararsız değişiklikler
potansiyel olarak yerine "kararsız olabilecek" veya "sağlam olmayabilecek". Stable=kararlı gibi bi kullanım var mı. Yoksa sağlam daha iyi gibi

2022-07-06 16:41 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Docker imajı derleyicinin yürütülebilir dosyasını çalıştırır, bu sayede tüm derleyici bağımsız değişkenlerini ona iletebilirsiniz.
bu sayede tüm değişkenleri derleyiciye iletebilirsiniz

2022-07-06 16:41 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Ayrıca standart bir JSON arayüzünü de kullanabilirsiniz (derleyiciyi araçlarıyla birlikte kullanırken tavsiye edilir).
~~bir~~ spesifik Solidity'nin JSON arayüzünden bahsediliyor. 

derleyiciyi kendi araçlarıyla değil genel anlamda kodlama ve derleme araçları burada bahsedilen. Hardhat, Truffle vs. gibi

2022-07-06 16:41 UTC, kuzdogan commented on docs/installing-solidity.rst
> +  başlıklarıyla ve hoşgörülü CORS yapılandırmasıyla sunulur.
lenient=serbest dersek daha açık olur. Aslında hoşgörülü de güzelmiş ama biraz anlaşılırlığı azaltıyor.

2022-07-06 16:41 UTC, kuzdogan commented on docs/installing-solidity.rst
> +- İşlem biçiminde ``commit.GITHASH``
``commit.GITHASH`` formatında sürüm commit'i

commit'i diğer yerlerde çevirmemişiz. Commit olarak kalsın bu durumda

2022-07-06 17:16 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +Docker imajı derleyicinin yürütülebilir dosyasını çalıştırır, bu sayede tüm derleyici bağımsız değişkenlerini ona iletebilirsiniz.
Tamamdır 👍

2022-07-06 17:17 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +  başlıklarıyla ve hoşgörülü CORS yapılandırmasıyla sunulur.
Tamamdır hocam 👍

2022-07-06 17:18 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +- İşlem biçiminde ``commit.GITHASH``
Tamamdır hocam 👍

2022-07-07 08:36 UTC, muratartan commented on docs/installing-solidity.rst
> +Yayınlanan en son sürüm için ``stable`` etiketini ve geliştirme kolundaki (branch) potansiyel olarak kararsız değişiklikler
"unstable" karşılığı olarak "stabil olmayan" denilebilir.

2022-07-07 14:53 UTC, muratartan reviewed
eline sağlık, metinde çokça geçen "nightly" kavramı  Türkçeleştirilmeden kullanılabilir bence, ya her defasında ya da ilk geçtiği yerde parantez içinde Türkçesi yazılarak (ki ben bunu öneriyorum, bilimsel makalelerde de hep böyle yapılır) kullanılabilir. Biz hem yeni başlayan birini hem de biraz tecrübeli insanları hedef alırsak insanların bazı kavramları orjinal haliyle bilip öğrenmesine de ön ayak olmalıyız düşüncesindeyim.

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Solidity Derleyicisini İndirme
"indirme" yerine "yükleme" desek nasıl olur?

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Sözleşmelerin gönderimini yaparken Solidity'nin yayınlanan en son sürümünü kullanmalısınız. Bunun nedeni,
deploy sözcüğünün yazılımda "yayına almak, devreye sokmak/almak" gibi bir anlamı var, bence "sözleşmelerin gönderimini yaparken" değil de "sözleşmeler yayına alınırken" denmesini tercih ederim, daha anlaşılır oluyor gibi. Ya da "gönderim" diyeceksek o zaman nereye gönderiyoruz bunu ilaveten belirtebiliriz yani "sözleşmeler EVM ye gönderilirken" gibi.

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +olarak, ana sürüm 0'a (yani 0.x.y) sahip yama düzeyindeki sürümler, kırılma değişiklikleri(breaking changes)
"kırılma değişiklikleri" derken ne denmek istendiğini yani terim olarak manasını parantez içinde açıklasak mı? Ya da dipnot olarak düşsek mi? Okuyan kişi bu haliyle anlayamaz.

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +*Solidity'i hızlı bir şekilde öğrenmeniz ve küçük akıllı sözleşmeleriniz için Remix'i kullanmanızı tavsiye ediyoruz.*
küçük akıllı sözleşmeler geliştirmek için...

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +`Remix'i online bir şekilde kullanabilirsiniz <https://remix.ethereum.org/>`_, bunun için herhangi bir şey indirmenize gerek yoktur.
```suggestion
`Remix'i online bir şekilde kullanabilirsiniz <https://remix.ethereum.org/>`_, bunun için herhangi bir şey indirip kurmanıza gerek yoktur.
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +the full-featured compiler, ``solc``.ref:`commandline-compiler`(komut satırı derleyicisi) belgeleri
the full-featured compiler, ``solc``.

burası fazla kalmış sanırım burada,bir kontrol eder misin?

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +bakımını doğrudan bizim tarafımızdan yapılmamaktadır. Ama bu konuda endişelenmenize gerek
```suggestion
bakımı doğrudan bizim tarafımızdan yapılmamaktadır. Ama bu konuda endişelenmenize gerek
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +İstediğiniz bir sürümün commit hash'ini kopyalayıp ve kendi makinenizde kontrol edebilirsiniz.
```suggestion
İstediğiniz bir sürümün commit hash'ini kopyalayabilir ve kendi makinenizde kontrol edebilirsiniz.
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +  IPFS aracılığıyla veya yerel olarak önbelleğe aldığınız) ve indirdikten sonra ikili sayı sistemi dosyaların hash'lerini
```suggestion
  IPFS aracılığıyla veya yerel olarak önbelleğe aldığınız) ve indirdikten sonra ikili sayı sistemi dosyalarının hash'lerini
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +  doğruladığınız sürece, ikili dosyaların için HTTPS protokolünü kullanmanız gerekmez.
```suggestion
  doğruladığınız sürece, ikili dosyalar için HTTPS protokolünü kullanmanız gerekmez.
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +  kendiniz çözmeniz gerekebileceğini unutmayın.
```suggestion
  kendiniz çözümlemeniz gerekebileceğini unutmayın.
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +olarak düzeltilmesinden kaynaklanmaktadır. Bu `hızlı versiyon değişiklilerini belirtmek için <https://semver.org/#spec-item-4>`_
```suggestion
olarak düzeltilmesinden kaynaklanmaktadır. Bu `hızlı versiyon değişikliklerini belirtmek için <https://semver.org/#spec-item-4>`_
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +    adresine kullanmaya devam edin. Bu, temeldeki barındırma hizmeti üzerinde şeffaf bir şekilde
"barındırma hizmeti" nden kastın "hosting" oldugunu belirtirsek okuyucu ne kastedildiğini anlar, yani parantez içinde hosting desek iyi olmaz mı?

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Aşağıda Solidity'nin tüm yapıları için bağımlılıklar verilmiştir:
yapılar değil de "geliştirmeler" mi desek acaba?

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +    0.5.10'dan başlayarak Boost 1.70+ kadar olan sürümlerle bağlantı kurmak manuel müdahale olmadan çalışmalıdır.
Buraya Kaan hoca bir baksa mı? linking den kasıt tam olarak nedir acaba? @kuzdogan

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Kaynak kodunu klonlamak aşağıdaki komutu çalıştırın:
```suggestion
Kaynak kodunu klonlamak için aşağıdaki komutu çalıştırın:
```

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Komut Satırı Derlemek
"komut satırı derlemesi" ya da "komut satırı kullanarak derlemek" ya da "komut satırından derlemek"

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +bu dosyaya çift tıklamak da Visual Studio'nun açılmasına neden olmalıdır.  Biz **Yayın**
"Ayrıca bu dosyaya çift tıklandığında Visual Studio nun açılması gerekir." desek bizim dilimizdeki söyleme daha uygun olur gibi.

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +Solidity, SMT çözücülerine karşı derlenebilir ve sistemde bulunurlarsa standart
standart yerine "default (varsayılan)" şeklinde mi desek? Default zaten bilinmesi gereken bir sözcük sadece yeni başlayanlar için parantez içinde varsayılan oldugunu belirtsek?

2022-07-07 14:53 UTC, muratartan commented on docs/installing-solidity.rst
> +(merge) , sürüm SemVer'e ve değişikliğin ciddiyetine göre yükseltilmelidir. Son olarak, bir
```suggestion
(merge) , SemVer'e ve değişikliğin ciddiyetine göre sürüm yükseltilmelidir. Son olarak, bir
```

2022-07-07 19:16 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Solidity Derleyicisini İndirme
Yüklemek daha doğru 👍 dowload değil

2022-07-07 19:17 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Solidity versiyonları `Semantic Versiyonlamayı <https://semver.org>`_ takip eder. Ek
Ya sürüm ya versiyon kullanalım tutarlılık açısından

2022-07-07 19:37 UTC, kuzdogan commented on docs/installing-solidity.rst
> +    0.5.10'dan başlayarak Boost 1.70+ kadar olan sürümlerle bağlantı kurmak manuel müdahale olmadan çalışmalıdır.
Linking'den kasıt bi programı derledikten (bytecode'a çevirdikten) sonra program dışında tanımlanmış fonksiyonlara vs. bağlamak. Mesela bi "print()" içeren basit bi programı derledikten sonra bu print fonsiyonunun tanımlandığı standart library'e bağlanması lazım, yani print'in tanımlandığı yere. 

"bağlamak" kullanılmış. Compilation bağlamında anlaşılır oluyor yine de parantez içinde (link) deneiblir.

2022-07-07 19:38 UTC, kuzdogan commented on docs/installing-solidity.rst
> +    0.5.10'dan başlayarak Boost 1.70+ kadar olan sürümlerle bağlantı kurmak manuel müdahale olmadan çalışmalıdır.
Burada linking güzel açıklanmış https://stackoverflow.com/questions/3322911/what-do-linkers-do

2022-07-13 07:39 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +Sözleşmelerin gönderimini yaparken Solidity'nin yayınlanan en son sürümünü kullanmalısınız. Bunun nedeni,
İkinicisi daha doğru gibi hocam

2022-07-13 07:42 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +olarak, ana sürüm 0'a (yani 0.x.y) sahip yama düzeyindeki sürümler, kırılma değişiklikleri(breaking changes)
Kavram dizinine ekleyelim en son onları dipnot olarak açıklayalım bence.

2022-07-13 07:53 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +Komut Satırı Derlemek
2. si daha uygun hocam sanki

2022-07-13 08:17 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +Ayrıca standart bir JSON arayüzünü de kullanabilirsiniz (derleyiciyi araçlarıyla birlikte kullanırken tavsiye edilir).
"Ayrıca spesifik bir JSON arayüzünü de kullanabilirsiniz (Hardhat,Truffle gibi derleyiciyi araçlarıyla birlikte kullanırken tavsiye edilir)." Bu şekilde dipnot ekledim

2022-07-13 08:29 UTC, AliErcanOzgokce commented on docs/installing-solidity.rst
> +olarak, ana sürüm 0'a (yani 0.x.y) sahip yama düzeyindeki sürümler, kırılma değişiklikleri(breaking changes)
Kavram dizinine açıklamasını ekledim.

2022-07-15 16:25 UTC, kuzdogan requested changes

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Sözleşmelerin sözleşmeler ESM'ye gönderilirken Solidity'nin yayınlanan en son sürümünü kullanmalısınız. Bunun nedeni,
```suggestion
Sözleşmeleri derleyip yüklerken Solidity'nin yayınlanan en son sürümünü kullanmalısınız. Bunun nedeni,
```

Yazım hatası ve "deploy"

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +*Solidity'i hızlı bir şekilde öğrenmeniz ve küçük akıllı sözleşmeler geliştirmek için Remix'i kullanmanızı tavsiye ediyoruz.*
```suggestion
*Solidity'i hızlı bir şekilde öğrenmek ve küçük akıllı sözleşmeler geliştirmek için Remix'i kullanmanızı tavsiye ediyoruz.*
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +açıklanacak olan derleyiciye erişim yollarından daha az özelliğe sahiptir. ``solc``.ref:`commandline-compiler`(komut satırı derleyicisi) belgeleri
```suggestion
açıklanacak olan derleyiciye erişim yollarından daha az özelliğe sahiptir. ``solc``.ref:`commandline-compiler`(komut satırı derleyicisi) dokümentasyonu
```
Documentation=dokümantasyon demişiz repo'da

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +    ``solcjs`` komut satırı seçenekleri ``solc`` ile uyumlu değildir. Ve aynı zamanda çalışmak için ``solc``’un davranışını
```suggestion
    ``solcjs`` komut satırı seçenekleri ``solc`` ile uyumlu değildir. Aynı zamanda çalışmak için ``solc`` komutuna
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +    bekleyen araçlar (örneğin ``geth`` gibi) ``solcjs`` ile çalışmayacaktır.
```suggestion
    ihtiyaç duyan araçlar (örneğin ``geth`` gibi) ``solcjs`` ile çalışmayacaktır.
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Örneğin, aşağıdaki komut ``solc`` imajının kararlı bir sürümünü çeker (zaten sahip değilseniz) ve ``--help`` parametresini ileterek
```suggestion
Örneğin, aşağıdaki komut ``solc`` imajının (elinizde mevcut değilse) kararlı bir sürümünü çeker  ve ``--help`` parametresini ileterek
```

Akıcılık için öne alalım. Sahipliktense mevcut olmak daha uygun

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Etikette, örneğin 0.5.4 sürümü için oluşturulmuş derleme sürümlerini de belirtebilirsiniz.
```suggestion
Etikette derleme sürümlerini de belirtebilirsiniz, örneğin 0.5.4 sürümü için:
```
Aşağıda örnek devam ediyor

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
>  Linux Packages
```suggestion
Linux Paketleri
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +bakımı doğrudan bizim tarafımızdan yapılmamaktadır. Ama bu konuda endişelenmenize gerek
Endişelenme kısmını silelim. "Fakat bu paketler..." desek yeterli

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Statik İkili Sayı Sistemleri
Binary'ler olarak kalsa daha iyi veya belki ham dosya diyebiliriz ama ikili sayı sistemi olmamış. Bi sayı sisteminden bahsedilmiyor burada.

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Bu depo, son kullanıcıların ikili dosya sistemlerini kullanıma hazır hale getirmeleri için hızlı ve kolay bir yol
yine binary. Hepsi için yorum koymuyorum ctrl+f ile bakılabilir

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +  bulunan bir kısayol bağlantısı veya yönlendirme sağlanmadan kaldırılamaz veya taşınamaz. Ayrıca bu dosyalar
```suggestion
  bulunan bir kısayol bağlantısı veya yönlendirme sağlanmadan kaldırılmaz veya taşınmaz. Ayrıca bu dosyalar
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +  hiçbir zaman değiştirilemez ve her zaman orijinal  sağlama toplamı ile eşleşmelidirler. Buradaki tek istisna,
```suggestion
  hiçbir zaman değiştirilmez ve her zaman orijinal  sağlama toplamı ile eşleşmelidirler. Buradaki tek istisna,
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +   - En iyi performansı istiyorsanız ``bin/`` yerine ``emscripten-wasm32/`` (``emscripten-asmjs/`` geri
fallback son çare anlamında. son çare (fallback) şeklinde yazalım

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +     ``solc-bin`` için de geçerlidir. Yeni alan adı önerisinde bulunulsa da, eski alan adı hala tam olarak
```suggestion
     ``solc-bin`` için de geçerlidir. Yeni alan adı önerilse de, eski alan adı hala tam olarak
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Aşağıdaki C++ derleyicileri ve minimum sürümleri Solidity kod tabanını oluşturabilir:
```suggestion
Aşağıdaki C++ derleyicileri ve minimum sürümleri Solidity kod tabanını derleyebilir:
```
Bu bağlamda derlemek daha uygun gibi oluşturmak muğlak kalıyor

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +macOS ve diğer Unice'lerde de oldukça benzerdir:
```suggestion
macOS ve diğer Unix'lerde de oldukça benzerdir:
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Sürüm Dizgisi Detayları
```suggestion
Sürüm Dizgisi (String) Detayları
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +- Commit biçiminde ``commit.GITHASH``
```suggestion
- ``commit.GITHASH`` biçiminde ilgili commit 
```

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +Yerel değişiklikler varsa işleme ``.mod`` diye eklenir.
```suggestion
Yerel değişiklikler varsa commit'in sonuna ``.mod`` diye eklenir.
```
Tutarlı kalalım sadece "commit" ile

2022-07-15 16:25 UTC, kuzdogan commented on docs/installing-solidity.rst
> +4. İşleyişi bozan değişiklikler tanıtıldı --> version 0.5.0'a yükseltildi.
Burada "işleyişi bozan" şeklinde çevirmişiz. Yukarıda "kırılma değişiklikleri" deniyordu. Bu daha güzel karşılıyor sanki.

2022-07-22 06:10 UTC, merged