Ref: #16 / Structure Of A Contract Çevirisi
solidity-docs/tr-turkish pull request #22
Opened 2022-07-06 20:38 UTC by muratartan

## Referans Alınan Issue
ref: #16 
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 72
- satır: 75-76
- satır: 107

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- 

## Ek Açıklamalar (Opsiyonel)
- struct, class, modifier vb gibi kavramların parantez içerisinde Türkçe karşılığı sadece sayfa içerisinde ilk bahsi geçtiği yerde
yazılıp sayfanın diğer yerlerinde sadece İngilizce adı olacak şekilde Türkçe'ye çevrilmemesi taraftarıyım. Bu terimler kod yazarken orjinal adlarıyla kullanıldığından dökümanda sürekli Türkçe karşılığının yazılması bana gereksiz geliyor hatta benim anlamamı da zorlaştırıyor. Bence kodda yazıldığı gibi kalmalı, yani örneğin sözcük struct ise dökümanda da hep struct olarak geçmeli diye düşünüyorum.

## Kontrol Listesi
- [x] Çeviri için son kontrolleri yaptım.
- [x] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-07-07 19:10 UTC, kuzdogan commented on docs/structure-of-a-contract.rst
> +Ayrıca, sözleşmeler bilgileri diğer sözleşmelerden miras alabilir.
inheritance = kalıt almak olarak geçmiş bence daha uygun
http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm
https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf

2022-07-07 19:15 UTC, kuzdogan commented
İngilizce terimi parantez içinde yazmanın amacı neye ithafen kelimenin söylendiğini bildirip devamında o kelimeyi kullanabilmek. Daha sonra bu kelimeler kelime dizinine eklenebilir. Tam tersi kullanım pek mantıklı gelmedi. 

Kelimeleri çevirme konusunda da çevirmenler inisiyatif alabilir. Örneğin `string`'i doğrudan kullanmak iyi olmuş sicim vs. kullanmak yerine ama "struct", "type" gibi kelimelerin çevirileri anlamı karşılıyor. Zamanla oturacaktır bu terimler.

2022-07-29 14:06 UTC, AliErcanOzgokce reviewed
Ufak bir şeyler önerdim onun dışında eline sağlık

2022-07-29 14:06 UTC, AliErcanOzgokce commented on docs/structure-of-a-contract.rst
> +Fonksiyon Değiştiriciler
```suggestion
Fonksiyon Modifierları
```

2022-07-29 14:06 UTC, AliErcanOzgokce commented on docs/structure-of-a-contract.rst
> +Fonksiyon Değiştiriciler
Hocam bence modifier'ı çevirmeden bırakalım, çünkü gerçekten anlaşılmayı çok zorlaştırıyor

2022-07-29 14:06 UTC, AliErcanOzgokce commented on docs/structure-of-a-contract.rst
> +Olaylar
```suggestion
Events (Olaylar)
```

2022-07-29 14:06 UTC, AliErcanOzgokce commented on docs/structure-of-a-contract.rst
> +Olaylar
Aynı şey Events için de geçerli

2022-07-29 14:06 UTC, AliErcanOzgokce commented on docs/structure-of-a-contract.rst
> +Yapı Tipleri
```suggestion
Struct (Yapı) Tipleri
```

2022-08-04 16:49 UTC, sevvalmutlu requested changes
Emeğine sağlık, genel olarak çok başarılı cümleler :)

2022-08-04 16:49 UTC, sevvalmutlu commented on docs/structure-of-a-contract.rst
> +bir sözleşme içinde tanımlanırlar, ancak sözleşmelerin dışında da tanımlanabilirler.
Öncelikle cümle anlamsal olarak gayet doğru fakat kulağa daha türkçe gelmesi açısından : 
```suggestion
genellikle bir sözleşme içinde tanımlanabilecekleri gibi, sözleşmelerin dışında da tanımlanabilirler.
```

2022-08-04 16:49 UTC, sevvalmutlu commented on docs/structure-of-a-contract.rst
> +    // Helper fonksiyonu sözleşmenin dışında tanımlı
```suggestion
    // Helper fonksiyonu sözleşmenin dışında tanımlanmıştır.
```

2022-08-04 16:49 UTC, sevvalmutlu commented on docs/structure-of-a-contract.rst
> +Fonksiyon Değiştiriciler
bence parantez içinde modifierları olarak da verilebilir anlamı karşılıyorsa

2022-08-08 14:25 UTC, muratartan commented
önerileriniz için teşekkürler değişiklikler yaptım, ancak @AliErcanOzgokce nin önerdiği mesela "Events (Olaylar)" gibi değişiklikleri tam tersi "Olaylar (Event)" şeklinde yaptım çünkü konu açıklamalarında da hep olay demişim, eğer açıklamalarda da bütün olay sözcüklerini event yapalım derseniz tekrar değiştiririm. Dokümanın diğer yerleriyle uyumluluk olmalı, her yerde event demeliyiz ya da her yerde olay demeliyiz. Beni bilgilendirirseniz ona göre değiştiririm.

2022-08-08 14:47 UTC, AliErcanOzgokce commented
> önerileriniz için teşekkürler değişiklikler yaptım, ancak @AliErcanOzgokce nin önerdiği mesela "Events (Olaylar)" gibi değişiklikleri tam tersi "Olaylar (Event)" şeklinde yaptım çünkü konu açıklamalarında da hep olay demişim, eğer açıklamalarda da bütün olay sözcüklerini event yapalım derseniz tekrar değiştiririm. Dokümanın diğer yerleriyle uyumluluk olmalı, her yerde event demeliyiz ya da her yerde olay demeliyiz. Beni bilgilendirirseniz ona göre değiştiririm.

Ben kendi çevirilerimde direk "event" diye kullanıyorum. Ayrıca bana göre solidity syntax'ın da bulunan bir terim olduğu için "olay" diye çevirmek doğru değil. Ama yine de yoruma açık

2022-08-28 21:20 UTC, merged