Ref: #17 / Types Çevirisi
solidity-docs/tr-turkish pull request #24
Opened 2022-07-08 19:27 UTC by alpertncc

## Referans Alınan Issue
ref: #17 

## Gözden Geçirilmesini İstediğim Satırlar
- /types klasörü içerisindeki tüm dokümanlar
- types.rst dosyasının tamamı

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- Kelime = _Bulduğum Kavram_  "[Referans Linki](https://sozluk.gov.tr/)"

## Ek Açıklamalar (Opsiyonel)
Bazı çevirilerin yanına orijinal kelimeleri de ekledim. Bu şekilde anlatılanın karşıya daha iyi aktarılabileceğini düşündüm. 
_Mapping_ kelimesinin çevirisi _Eşleme_ olarak yapıldı.

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [ ] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-07-14 09:29 UTC, AliErcanOzgokce commented
PR isteği oluştururken yalnızca çevirdiğin sayfaya özel olarak yeni bir branch açman lazım. Burda sen develop ana branch'inden PR oluşturmuşsun.

2022-07-15 22:44 UTC, kuzdogan requested changes
operators.rst'ye kadar bakabildim

2022-07-15 22:44 UTC, kuzdogan commented on docs/types.rst
> +Solidity statik olarak yazılmış bir dildir, bu, her bir değişkenin türünün (durum ve yerel) belirtilmesi gerektiği anlamına gelir.
```suggestion
Solidity statik olarak türlenmiş bir dildir, bu, her bir (durum ve yerel) değişkenin türünün  belirtilmesi gerektiği anlamına gelir.
```
parantezi değişkenden önce alınca tür'le değil değişken'le alakalı olduğu daha açık oluyor

2022-07-15 22:44 UTC, kuzdogan commented on docs/types.rst
> +Solidity'de "tanımsız" veya "boş" değerler kavramı yoktur, yeni bildirilen değişkenlerin türüne bağlı olarak her zaman :ref:`varsayılan bir değeri<default-value>` vardır.
```suggestion
Solidity'de "tanımsız" veya "boş" (null) değerler kavramı yoktur, yeni bildirilen değişkenlerin türüne bağlı olarak her zaman :ref:`varsayılan bir değeri<default-value>` vardır.
```
parantezde eklersek daha açık olur. GLOSSARY'e de ekleyelim

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Örtülü tür dönüşümü, argümanları fonksiyonlara iletmek ya da operatör atamaları sırasında, derleyici tarafından
```suggestion
Örtülü tür dönüşümü, argümanları fonksiyonlara iletme ya da operatör atamaları sırasında, derleyici tarafından
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Örnek vermek, ``uint8`` türü,
```suggestion
Örneğin, ``uint8`` türü,
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Bir operatör diğer türlere uygulanırsa, derleyici işlenenlerden birini örtük olarak diğerinin türüne dönüştürmeye çalışır (aynısı atamalar için de geçerlidir).
```suggestion
Bir operatör birbirinden farklı türlere uygulanırsa, derleyici işlenenlerden birini örtük olarak diğerinin türüne dönüştürmeye çalışır (aynısı atamalar için de geçerlidir).
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Bu kod bloğunun sonunda ``x``, ``0xfffff..fd`` (64 adet onaltılık karaker) değerine sahip olacaktır, bu, ikisinin 256 bitlik tümleyen temsili olan -3'tür.
```suggestion
Bu kod bloğunun sonunda ``x``, ``0xfffff..fd`` (64 adet onaltılık karaker) değerine sahip olacaktır, bu, iki'nin 256 bitlik tümleyen (two's complement) temsili olan -3'tür.
```
Burada "ikisi"nden değil de iki'nin tümleyeni'nden (two's complement) bahsediliyor.

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Sabit boyutlu bayt türleri, dönüşümler sırasında farklı davranır. Bireysel bayt dizileri olarak düşünülebilirler ve daha küçük bir türe dönüştürmek diziyi kesecektir:
"Sabit boyutlu bytes türleri" veya "sabit boyutlu bayt dizisi türleri" desek daha iyi gibi. Bu şekilde olursa baytların kendisi sabit boyutluymuş gibi oluyor ki bu zaten öyle. Sabit olduğu belirtilmek istenen dizinin uzunluğu.

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Sabit boyutlu bir bayt türü, daha büyük bir türe açıkça dönüştürülürse, elde edilen ortak tümleyen sağ tarafta doldurulur. Sabit bir dizindeki bayta erişmek, dönüştürmeden önce ve sonra aynı değerle
Yukarıdakine göre yine fixed-size bytes

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Değişmezler ve Temel Türler Arasındaki Dönüşümler
literal !== değişmez

Değişmez olarak "constant" ve "immutable"lar var

sayı değeri gösterimi anlamında `uint9 a = 12`'deki 12 gibi. 

Burada ifade denmiş: https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> +Dize (String) değişmezleri ve onaltılı dize değişmezleri, karakter sayıları bayt türünün boyutuyla eşleşiyorsa, örtük olarak sabit boyutlu bayt dizilerine dönüştürülebilir:
String'leri string olarak mı bıraksak? Bunu grupta konuşup bi ortak karara bağlayabiliriz. Dizi'lerle (array) karışıyor çünkü

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/conversion.rst
> + :ref:`adres_değişmezleri` böümünde açıklandığı gibi, sağlama toplamı testini geçen doğru boyuttaki onaltılık değişmezler ``address`` türündedir. Başka hiçbir değişmez ``address`` türüne örtük olarak
```suggestion
 :ref:`adres_değişmezleri` böümünde açıklandığı gibi, sağlama toplamı (checksum) testini geçen doğru boyuttaki onaltılık değişmezler ``address`` türündedir. Başka hiçbir değişmez ``address`` türüne örtük olarak dönüştürülemez.
```
ek olarak "literals"

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Eşleme türleri ``mapping(KeyType => ValueType)`` sözdizimi yapısını kullanır ve eşleme türünün değişlenleri, ``mapping(KeyType => ValueType) VariableName``sözdizimi kullanılarak bildirilir.
```suggestion
Eşleme türleri ``mapping(KeyType => ValueType)`` sözdizimi yapısını kullanır ve eşleme türünün değişkenleri, ``mapping(KeyType => ValueType) VariableName``sözdizimi kullanılarak bildirilir.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +``KeyType``, herhangi bir yerleşik değer türü, ``bytes``, ``string``, herhangi bir sözleşme ya da numaralandırma türü olabilir. Eşlemeler, yapılar veya dizi türleri gibi diğer kullanıcı tanımlı veya
```suggestion
``KeyType``, herhangi bir yerleşik değer türü, ``bytes``, ``string``, herhangi bir sözleşme ya da numaralandırma türü olabilir. Eşlemeler, yapılar veya dizi türleri gibi diğer kullanıcı tanımlı veya karmaşık türlere izin verilmez. ``ValueType``, eşlemeleri diziler ve yapılar dahil herhangi bir tür olabilir.  
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Eşlemeleri, olası her anahtarın var olduğu ve bir türün :ref:`varsayılan değeri <default-value>` olan bayt temsilinin tamamı sıfır olan bir değere eşlendiği şekilde sanal olarak başlatılan `karma tab
Karmaşık biraz cümle bölsek daha güzel olabilir:

"Eşlemeleri olası her anahtarın var olduğu sanal olarak başlatılan `karma tablolar <https://en.wikipedia.org/wiki/Hash_table>` olarak düşünebiliersiniz. Her bir anahtarın eşlendiği elemanın değerinin byte temsilinin tamamı sıfırdır, ki bu da bir türün varsayılan değeridir" 

Ek olarak "karma tablolar" mı diyoruz sanki bunları "hash tablosu" olarak bırakmıştık. Değilse GLOSSARY'e ekleyelim.

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Bu nedenle, eşlemelerin bir uzunluğu veya ayarlanan bir anahtar veya değer kavramı yoktur ve bu nedenle atanan anahtarlarla ilgili ek bilgi olmadan silinemezler (bkz. :ref:`eşlemeleri-silme`).
```suggestion
Bu nedenle, eşlemelerin bir uzunluğu veya ayarlanan bir anahtar veya değer kavramı yoktur ve bu nedenle atanan anahtarlarla ilgili ek bilgi olmadan silinemezler (bkz. :ref:`eşlemeleri-silme <clearing-mappings>`).
```

ref'in referans gösterdiği identifier'ı değiştirmeyelim ama hyperlink'in metnini değiştirebiliriz yukarıda yaptığımız gibi

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Eşlemeler yalnızca ``storage`` veri konumuna sahip olabilir ve bu nedenle, fonksiyonlardaki depolama referans türleri olarak veya kitaplık fonksiyonları için parametreler olarak durum değişkenleri iç
```suggestion
Eşlemeler yalnızca ``storage`` veri konumuna sahip olabilir ve bu nedenle, fonksiyonlardaki depolama referans türleri olarak veya kitaplık fonksiyonları için parametreler olarak durum değişkenleri için izin verilir. Bunlar, genel olarak görülebilen (public) sözleşme fonksiyonlarının parametreleri veya dönüş parametreleri olarak kullanılamazlar. Bu kısıtlamalar, eşlemeler içeren diziler ve yapılar için de geçerlidir.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Yinelenebilir Eşlemeler
```suggestion
Yinelenebilir (Iterable) Eşlemeler
```

Benim aklıma ilk recursive veya repeatable tarzı birşey geldi. Iterable diye düşelim

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/mapping-types.rst
> +Eşlemeleri yineleyemezsiniz, yani anahtarlarını numaralandıramazsınız. Yine de bunların üzerine bir veri yapısı uygulamak ve bunun üzerinde yineleme yapmak mümkündür. Örneğin, aşağıdaki kod, ``User``
```suggestion
Eşlemeleri yineleyemezsiniz, yani anahtarlarını numaralandıramazsınız. Yine de bunların üzerine bir veri yapısı uygulamak ve bunun üzerinde yineleme yapmak mümkündür. Örneğin, aşağıdaki kod, ``User`` sözleşmesinin daha sonra veri eklediği bir ``IterableMapping`` kitaplığı uygular ve ``sum`` fonksiyonu tüm değerleri toplamak için ``IterableMapping``'i yineler.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +1. Sağ işlenenin türü dolaylı olarak sol işlenenin türüne dönüştürülebiliyorsa,
```suggestion
1. Sağ işlenenin türü örtülü olarak sol işlenenin türüne dönüştürülebiliyorsa, 
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +2. Sol işlenenin türü dolaylı olarak sağ işlenenin türüne dönüştürülebiliyorsa,
```suggestion
2. Sol işlenenin türü örtülü olarak sağ işlenenin türüne dönüştürülebiliyorsa, 
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +İşlenenlerden birinin :ref:`gerçek sayı <rational_literals>` olması durumunda, ilk önce değeri tutabilen en küçük tür olan "mobil türe" dönüştürülür (aynı bit genişliğindeki işaretsiz türler, işaretl
```suggestion
İşlenenlerden birinin :ref:`sayı ifadesi <rational_literals>` olması durumunda, ilk önce değeri tutabilen en küçük tür olan "mobil türe" dönüştürülür (aynı bit genişliğindeki işaretsiz türler, işaretli türlerden "daha küçük" olarak kabul edilir) .
```
literal = ifade diyebiliriz burada da

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +Her ikisi de gerçek sayıysa, işlem keyfi bir kesinlikle hesaplanır.
```suggestion
Her ikisi de sayı ifadesiyse, işlem keyfi bir kesinlikle hesaplanır.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +Üçlü operatör, ``<expression> ? <trueExpression> : <falseExpression>`` formunda bulunan ifadelerin açıklanmasında kullanılır. Ana ``<expression>`` değerlendirmesinin sonucuna bağlı olarak verilen son
```suggestion
Üçlü operatör, ``<expression> ? <trueExpression> : <falseExpression>`` formunda bulunan ifadelerin açıklanmasında kullanılır. Ana ``<expression>`` değerlendirmesinin sonucuna bağlı olarak verilen son iki ifadeden birini değerlendirir. ``<expression>`` "doğru" olarak değerlendirilirse, ``<trueExpression>``  değerlendirilir, aksi takdirde ``<falseExpression>`` değerlendirilir.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +Üçlü operatörün sonucu, tüm işlenenleri rasyonel sayı değişmezleri olsa bile, bir rasyonel sayı türüne sahip değildir. Sonuç türü, iki işlenenin türlerinden yukarıdakiyle aynı şekilde belirlenir, ger
```suggestion
Üçlü operatörün sonucu, tüm işlenenleri rasyonel sayı ifadeleri olsa bile, bir rasyonel sayı türüne sahip değildir. Sonuç türü, iki işlenenin türlerinden yukarıdakiyle aynı şekilde belirlenir, gerekirse ilk önce mobil türlerine dönüştürülür.
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +Yapılar (structs) için, tüm üyelerin sıfırlandığı bir yapı atar. Başka bir deyişle, ``a``nın ``delete a``dan sonraki değeri, ``a``nın atama olmadan bildirilmesiyle aynıdır:
```suggestion
Yapılar (structs) için, tüm üyelerin sıfırlandığı bir yapı atar. Başka bir deyişle, ``a``nın ``delete a``dan sonraki değeri, ``a``nın atama olmadan bildirilmesiyle aynıdır. Fakat
```

2022-07-15 22:44 UTC, kuzdogan commented on docs/types/operators.rst
> +``delete`` fonksiyonunun eşlemeler üzerinde hiçbir etkisi yoktur (çünkü eşlemelerin anahtarları rastgele olabilir ve genellikle bilinmez). Bu nedenle, bir yapıyı silerseniz, eşleme olmayan tüm üyeler
```suggestion
``delete`` fonksiyonunun eşlemeler üzerinde hiçbir etkisi yoktur (çünkü eşlemelerin anahtarları rastgele olabilir ve genellikle bilinmez). Bu nedenle, bir yapıyı silerseniz, eşleme olmayan tüm üyeleri sıfırlar ve eşleme olmadıkça üyeleri özyineleyerek (recursive) siler. Ancak, tekil anahtarlar ve eşledikleri şey silinebilir: ``a`` bir eşleme ise, ``delete a[x]``, ``x``de depolanan değeri siler.
```

2022-07-31 08:43 UTC, alpertncc commented on docs/types/conversion.rst
> +Değişmezler ve Temel Türler Arasındaki Dönüşümler
Literals çevirisini İfadeler (Literals) şeklinde değiştiriyorum

2022-07-31 09:23 UTC, alpertncc commented on docs/types/conversion.rst
> +Değişmezler ve Temel Türler Arasındaki Dönüşümler
literal ifadeleri cümle yapısına göre tekrar çevrildi.

2022-07-31 09:33 UTC, alpertncc commented
Tüm review istekleri değerlendirildi ve dosyalar güncellendi.

2022-08-17 09:44 UTC, sevvalmutlu approved these changes

2022-08-17 09:44 UTC, sevvalmutlu commented on docs/types/conversion.rst
> +otomatik olarak uygulanır. Genel olarak, bilgi kaybı yoksa ve anlamsal açıdan bir sorun yoksa, değer türleri arasında bir örtülü dönüşüm mümkündür.
```suggestion
otomatik olarak uygulanır. Genel olarak, bilgi kaybı yoksa ve anlamsal açıdan bir sorun yoksa, değer türleri arasında örtülü bir dönüşüm mümkündür. 
```

2022-08-28 21:17 UTC, merged