Ref: #11 / Contracts Çevirisi
solidity-docs/tr-turkish pull request #30
Opened 2022-07-21 23:00 UTC by 0fatih

## Referans Alınan Issue
ref: #11
  
## Gözden Geçirilmesini İstediğim Satırlar

## Ek Açıklamalar (Opsiyonel)
Bazı temel kavramların çevrilmesi ortaya absürd bir anlam çıkardığı için bunları çevirmemeyi tercih ettim.

## Kontrol Listesi
- [x] Çeviri için son kontrolleri yaptım.
- [x] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-07-26 13:48 UTC, sevvalmutlu requested changes
contract kelimesinin genel olarak sözleşme olarak değiştirilmesi gerek diye düşünüyorum.
Ek olarak, 'Type' kelimesini tür ve tip olarak farklı farklı kullanmışsınız tip çok doğru bir kullanım olmuyor bu bağlamda tekrar gözden geçirebilirsiniz.

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
@AliErcanOzgokce Contract yerine türkçe bir söylem getirmek uygun olur mu hocam?

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/abstract-contracts.rst
> +constructor'larına argüman sağlamadıklarında abstract olarak tanımlanmalıdır.
Sözleşmeler, işlevlerinden en az biri uygulanmadığında veya bütün temel sözleme yapıcılar için argüman sağlamadığında abstract olarak işaretlenmelidir.

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/abstract-contracts.rst
> +Bu durumlardan herhangi birisi geçerli değilse bile bir contract abstract olarak işaretlenebilir.
birisi yerine 'biri'

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/abstract-contracts.rst
> +Abstract contractlar ``abstract`` olarak işaretlenerek belirtilir, aşağıdaki örnekteki gibi.
Aşağıdaki örnekte belirtildiği gibi, Abstract contractlar ``abstract`` olarak işaretlenerek belirtilir.

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/abstract-contracts.rst
> +Bu tip abstract contractlar direkt olarak örneklendirilemez. Bu ayrıca bütün fonksiyonlarını tanımlayan bir
Bu, abstract sözleşmenin kendisi tanımlanmış tüm işlevleri yerine getiriyorsa da geçerlidir.

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/visibility-and-getters.rst
> +``myArray(i)`` kullanarak çağırmanıza gerek kalmadı.
'kullanarak çağırmanıza gerek kalmadı' kısmı kulağa hoş gelmiyor.  şu şekilde değiştirilebilir:
Artık tüm dizine erişmek için her bir aramayı  tek bir öğeye döndüren ``myArray(i)`` yerine ``getArray()`` kullanabilirsiniz.

2022-07-26 13:48 UTC, sevvalmutlu commented on docs/contracts/using-for.rst
> +    // Şimdi tipe fonksiyonları ekliyoruz.
tip kullanımı buraya uygun değil 'Şimdi örneğe fonksiyonları ekliyoruz.' daha iyi olabilir

2022-07-26 13:58 UTC, AliErcanOzgokce commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
Sözleşeme diye çevirmiştik, bu tarz çevirdiğimiz kelimeleri [kavramlar dizinine](/GLOSSARY.md) ekliyoruz.

2022-07-27 08:47 UTC, 0fatih commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
Ben çeviriye başladığımda henüz liste yoktu o yüzden direkt olarak kullanmayı tercih ettim. Belki İngilizce kaynaklardan öğrendiğim içindir ama bana göre contract'a sözleşme demek biraz tuhaf geliyor. Bu arada contract'ın çevirisi belirttiğiniz yerde bulunmamakta, eklemeyi unuttunuz galiba.

2022-07-28 17:26 UTC, AliErcanOzgokce commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
Haklısınız eklemeyi unutmuşum. Contract konusuna gelirsek eğer bu konu yine tartışmaya açık. @kuzdogan @muratartan @sevvalmutlu @cdemircioglu

2022-07-29 16:03 UTC, AliErcanOzgokce commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
Bu konu hakkında issue açıldı (Ref: #45)

2022-08-09 19:06 UTC, AliErcanOzgokce commented on docs/contracts/abstract-contracts.rst
> +Abstract Contract'lar
@0fatih hocam, "Akıllı Sözleşme" şeklinde çevirilmesine karar verildi ona göre çevirinizi düzenlerseniz sevinirm.

2022-08-28 21:16 UTC, merged