Emreaslan
solidity-docs/tr-turkish pull request #35
Opened 2022-07-23 07:18 UTC by emreaslan-ea

## Referans Alınan Issue
ref: #29 
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 10
- satır: 14
- satır: 15

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)
Slot kelimesini yuva olarak kullanıp kullanmamakta kararsız kaldım ve ref#28 'i baz alarak bu şekilde kullandım.

## Kontrol Listesi
- [x] Çeviri için son kontrolleri yaptım.
- [x] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-07-23 11:36 UTC, AliErcanOzgokce reviewed
Bir kaç öneride bulundum. Onun dışında eline sağlık

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Solidity, belirli bayt aralıkları (uç noktalar dahil) aşağıdaki şekilde kullanılmak üzere dört adet 32 baytlık yuva ayırır:
```suggestion
Solidity, belirli bayt aralıklarını (uç noktalar dahil) aşağıdaki şekilde kullanılmak üzere dört adet 32 baytlık yuva ayırır:
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +- ``0x40`` - ``0x5f`` (32 bytes): Şuan ayrılmış olan bellek boyutu (boş bellek işaretçisi olarak da bilinir)
```suggestion
- ``0x40`` - ``0x5f`` (32 bytes): Şuan ayrılmış olan bellek boyutu (boş bellek pointer'ı olarak da bilinir)
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Durumlar arasında scratch alanı kullanılabilir (yani assembly içinde). Sıfır yuvası, dinamik bellek dizilerinin başlangıç
```suggestion
Durumlar arasında (yani assembly içinde) scratch alanı kullanılabilir. Sıfır yuvası, dinamik bellek dizilerinin başlangıç
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +değeri olarak kullanılır ve asla başlangıçta ``0x80``'i gösteren boş bellek işaretçi noktasına yazılmamalıdır.
```suggestion
değeri olarak kullanılır ve asla başlangıçta ``0x80``'i gösteren boş bellek pointer noktasına yazılmamalıdır.
```

Bence "pointer" kavramını çevirmemeliyiz. Anlamda bozukluk ortaya çıkarıyor. Hepsi için yorum oluşturmayacağım, "Ctrl+F" ile düzenleme yapabilirsin

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +hafıza asla serbest bırakılmaz (Bu gelecekte değişebilir).
```suggestion
hafıza asla serbest bırakılmaz (Bu özellik gelecekte değişebilir).
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Solidity'deki bellek dizilerindeki öğeler her zaman 32 baytın katlarını kaplar (Bu
```suggestion
Solidity'de bulunan bellek dizilerindeki öğeler her zaman 32 baytın katlarını kaplar (Bu 
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +.. Uyarı::
```suggestion
.. warning::
```
Bu kısımları çevirmemen lazım

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +  olmayabilir. Bu nedenle, boş hafıza noktasının hafızayı sıfırlaması beklenmemelidir.
```suggestion
  olmayabilir. Bu nedenle, boş hafızanın sıfırlanmış hafızayı göstermesi beklenmemelidir.
```
"point" burada işaret etmek, göstermek anlamında kullanılmış.

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Depolama Düzeni İle Farklılıkları
```suggestion
Depolama Düzeni Farklılıkları
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Aşağıda bazı örnekler var.
```suggestion
Aşağıda bunlara yönelik bazı örnekler bulunmaktadır.
```

2022-07-23 11:36 UTC, AliErcanOzgokce commented on docs/internals/layout_in_memory.rst
> +Yapı(Struct) Düzeninde Farklılıklarına Bir Örnek
```suggestion
Yapı(Struct) Düzeni Farklılıklarına Bir Örnek
```

2022-07-23 12:30 UTC, emreaslan-ea commented
Öneriler düzeltildi ve değiştirildi.

2022-07-26 13:01 UTC, sevvalmutlu requested changes
10-14-15 satırları inceledim 14 için bir yorumda bulundum geri kalanı iyi görünüyor, eline sağlık

2022-07-26 13:01 UTC, sevvalmutlu commented on docs/internals/layout_in_memory.rst
> +Durumlar arasında (yani assembly içinde) scratch alanı kullanılabilir. Sıfır yuvası, dinamik bellek dizilerinin başlangıç
'assembly içinde' yerine, 'Scratch aralığı, ifadeler arasında kullanılabilir (yani, satır içi assembly içinde). şeklinde kullanılabilir.

2022-08-28 21:48 UTC, merged