Grammar
solidity-docs/tr-turkish pull request #55
Opened 2022-08-02 19:07 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #54
  
## Gözden Geçirilmesini İstediğim Satırlar

### SolidityLexer.g4
- satır: 189-191
- satır: 344

### SolidityParser.g4
- satır: 76 (constructor/kurucu ?)
- satır: 315-316
- satır: 415
- satır: 543-544 (right-hand)

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- Sequence = Sıra
- Parser = Çözümleyici
- Aliases = Takma Adlar

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-08-16 20:47 UTC, sevvalmutlu requested changes

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Bir constructor tanımı.
Constructor'ın tanımı:

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Kullanıcı tanımlı bir değer tipinin tanımı. Bir kaynak birim içinde üst seviyede veya bir sözleşme, kütüphane veya arayüz içinde oluşabilir.
```suggestion
 * Kullanıcı tanımlı bir değer tipinin?? tip burada doğru bir kullanım mı emin değilim.

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Error parametresi.
```suggestion
 * Error parametresi. error'un hata olarak kullanılmama sebebi nedir?
```

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Bir tür adı bir temel tür, bir fonksiyon türü, bir mapping türü, bir kullanıcı tanımlı tür olabilir
```suggestion
 * Bir türün adı, temel tür,  fonksiyon türü, mapping türü,  kullanıcı tanımlı tür olabilir.
```

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Tam bir dize literali, bir veya birkaç ardışık tırnaklı dizeden oluşur.
```suggestion
 * Tam bir dize literali, bir veya birkaç ardışık alıntılanmış dizeden oluşur.
```

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Kıvırcık parantezli bir ifade bloğu. Kendi alanını açar.
```suggestion
Kıvrımlı parantezli ifadeler bloğu. Kendi kapsamını açar. 
```

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Bayrak olarak çift tırnaklı stringlerin virgülle ayrılmış listesi.
Bayrak olarak çift tırnak içine alınmış dizelerin virgülle ayrılmış listesi.

2022-08-16 20:47 UTC, sevvalmutlu commented on docs/grammar/SolidityParser.g4
> + * Değişken tanımlamalarında kullanılacak değişken adlarının bir demeti.
Değişken tanımlamalarında kullanılacak bir dizi değişken adı.

2022-08-28 22:16 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Error parametresi.
Çünkü solidity üzerinde Error bir fonksiyon olarak kullanılıyor

2022-09-08 13:57 UTC, AliErcanOzgokce reviewed
Genel yorumlar

2022-09-08 13:57 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Bir constructor tanımı.
```suggestion
 * Constructor'ın tanımı:
```

2022-09-08 13:57 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Kullanıcı tanımlı bir değer tipinin tanımı. Bir kaynak birim içinde üst seviyede veya bir sözleşme, kütüphane veya arayüz içinde oluşabilir.
```suggestion
 * Kullanıcı tanımlı bir değer türünün tanımı. Bir kaynak birim içinde üst seviyede veya bir sözleşme, kütüphane veya arayüz içinde oluşabilir.
```

2022-09-08 13:57 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Kıvırcık parantezli bir ifade bloğu. Kendi alanını açar.
```suggestion
 * Kıvrımlı parantezli ifadeler bloğu. Kendi kapsamını açar.
```

2022-09-08 13:57 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Bayrak olarak çift tırnaklı stringlerin virgülle ayrılmış listesi.
String'i dize olarak çevirmiyoruz çünkü array ile karışıyor.

2022-09-08 13:57 UTC, AliErcanOzgokce commented on docs/grammar/SolidityParser.g4
> + * Değişken tanımlamalarında kullanılacak değişken adlarının bir demeti.
```suggestion
 * Değişken tanımlamalarında kullanılacak bir dizi değişken adı.
```

2022-09-08 13:58 UTC, merged