Ref: #21 / Control Structures Çevirisi
solidity-docs/tr-turkish pull request #65
Opened 2022-08-11 08:35 UTC by kuzdogan

## Referans Alınan Issue
ref: #21
  
## Gözden Geçirilmesini İstediğim Satırlar

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- metadata = [meta veri](https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf)
- bytecode = byte kod
- mapping = [eşleme](https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf)
- array = dizi ([1](http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm), [2](https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf))
- encoding = kodlama
- decoding = çözme
- pattern = örüntü
- parser = [ayrıştırıcı](https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf)

## Ek Açıklamalar (Opsiyonel

## Kontrol Listesi
- [x] Çeviri için son kontrolleri yaptım.
- [x] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-08-17 09:07 UTC, sevvalmutlu approved these changes

2022-09-10 11:15 UTC, AliErcanOzgokce requested changes
Birkaç tane yazım yanlışı buldum onun dışında eline sağlık

2022-09-10 11:15 UTC, AliErcanOzgokce commented on docs/metadata.rst
> +            // peephole'ün varayılanı "true"dur
```suggestion
            // peephole'ün varsayılanı "true"dur
```

2022-09-10 11:15 UTC, AliErcanOzgokce commented on docs/metadata.rst
> +            // inliner'ın varayılanı "true"dur
```suggestion
            // inliner'ın varsayılanı "true"dur
```

2022-09-10 11:15 UTC, AliErcanOzgokce commented on docs/metadata.rst
> +            // jumpdestRemover'ın varayılanı "true"dur
```suggestion
            // jumpdestRemover'ın varsayılanı "true"dur
```

2022-09-10 11:15 UTC, AliErcanOzgokce commented on docs/metadata.rst
> +            // Opsyionel: Yalnızca "yul" "true" ise mevcut
```suggestion
            // Opsiyonel: Yalnızca "yul" "true" ise mevcut
```

2022-09-13 15:12 UTC, merged