Ref: #59 / Yul Çevirisi
solidity-docs/tr-turkish pull request #67
Opened 2022-08-18 12:28 UTC by muratartan

## Referans Alınan Issue
ref: #59 
  
## Gözden Geçirilmesini İstediğim Satırlar
- _satır: 183_
- _satır: 194-196_
 - _satır: 614-615_
 - _satır: 635_
 - _satır: 637_
 - _satır: 1253_

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)
- big-endian

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [ ] Çeviri için son kontrolleri yaptım.
- [ ] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-09-08 15:00 UTC, sevvalmutlu approved these changes

2022-09-10 11:11 UTC, AliErcanOzgokce requested changes
Gözden geçirilmesi istenen satırlara baktım onun dışında elinize sağlık

2022-09-10 11:11 UTC, AliErcanOzgokce commented on docs/yul.rst
> +- Bir onaltılık dize, önce her bir bitişik onaltılık basamak çifti
```suggestion
- Bir onaltılık string, önce her bir bitişik onaltılık basamak çifti 
```
Dize, dizi bunlar karışabiliyor o yüzden string şeklinde kullanmak daha mantıklı bence

2022-09-10 11:11 UTC, AliErcanOzgokce commented on docs/yul.rst
> +AST'nin çeşitli düğümlerinde aşırı yüklenmiş bir E değerlendirme fonksiyonu
"Düğüm" yerine direk "Node" diye mi kullansak?

2022-09-10 11:11 UTC, AliErcanOzgokce commented on docs/yul.rst
> +Varsayılan olarak Yul optimizer, önceden tanımlanmış optimizasyon adımları dizisini oluşturulan assembly'ye uygular.
```suggestion
Varsayılan olarak Yul optimizer(optimize edici), önceden tanımlanmış optimizasyon adımları dizisini oluşturulan assembly'ye uygular. 
```
Parantez içinde belirtilebilir ama zorunlu değil bence yoruma açık

2022-09-18 11:47 UTC, AliErcanOzgokce commented on docs/yul.rst
> +AST'nin çeşitli düğümlerinde aşırı yüklenmiş bir E değerlendirme fonksiyonu
```suggestion
AST'nin çeşitli düğümlerinde(node) aşırı yüklenmiş bir E değerlendirme fonksiyonu 
```

2022-09-18 11:47 UTC, merged