Ref: #70 / Using The Compiler Çevirisi
solidity-docs/tr-turkish pull request #71
Opened 2022-08-25 16:26 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #70
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 33;
- satır: 38;
- satır: 52-56;
- satır: 66-68;
- satır: 73;
- satır: 94;
- satır: 158;
- satır: 170 (🇹🇷🇹🇷🇹🇷);
- satır: 174;
- satır: 252-253 (NOTE, WARNING);
- satır: 382;
- satır: 530

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-09-12 09:40 UTC, sevvalmutlu requested changes

2022-09-12 09:40 UTC, sevvalmutlu commented on docs/using-the-compiler.rst
> +   - Gaz tahmini ve optimize edici ile ilgili diğer hesaplara erişim için gaz maliyeti arttı.
```suggestion
   - Gaz tahmini ve optimize edici ile ilgili diğer hesaplara erişim için gaz maliyeti arttırıldı.
```

2022-09-12 09:40 UTC, sevvalmutlu commented on docs/using-the-compiler.rst
> +| Modil                      | Versiyon| Açıklama                                         |
```suggestion
| Modül                      | Sürüm | Açıklama                                         |
```

2022-09-13 15:15 UTC, AliErcanOzgokce commented on docs/using-the-compiler.rst
> +| Modil                      | Versiyon| Açıklama                                         |
```suggestion
| Modül                      | Versiyon| Açıklama                                         |
```

2022-09-13 15:15 UTC, merged