Ref: #72 / Contributing Çevirisi
solidity-docs/tr-turkish pull request #73
Opened 2022-08-27 13:01 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #72
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 88
- satır: 107
- satır: 398-410
- satır: 412

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-09-12 09:49 UTC, sevvalmutlu requested changes

2022-09-12 09:49 UTC, sevvalmutlu commented on docs/contributing.rst
> +Tüm derleyici testlerini çalıştırmak için isteğe bağlı olarak birkaç dependencies
```suggestion
Tüm derleyici testlerini çalıştırmak için isteğe bağlı olarak birkaç bağlayıcı faktör yüklemek isteyebilirsiniz.
```

2022-09-12 09:49 UTC, sevvalmutlu commented on docs/contributing.rst
> +macOS üzerinde bazı test betikleri GNU coreutils'in kurulu olmasını beklemektedir.
```suggestion
macOS üzerinde bazı test komut dosyaları GNU coreutils'in kurulu olmasını beklemektedir.
```

2022-09-15 19:01 UTC, cdemircioglu commented on docs/contributing.rst
> +- Pazartesi günleri saat 15:00 CET/CEST.
```suggestion
- Pazartesi günleri saat 15:00 CET/CEST. Turkiye saati ile 16:00, 
```

2022-09-18 11:29 UTC, merged