Ref: 74 / 080 Breaking Changes Çevirisi
solidity-docs/tr-turkish pull request #75
Opened 2022-08-27 13:33 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #74
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 9
- satır: 40-91

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-09-08 14:54 UTC, sevvalmutlu requested changes

2022-09-08 14:54 UTC, sevvalmutlu commented on docs/080-breaking-changes.rst
> +  Bu, üs alma operatörünü ayrıştırmanın yaygın yoludur.
```suggestion
  Bu, üst alma operatörünü ayrıştırmanın yaygın yoludur.
```

2022-09-08 14:54 UTC, sevvalmutlu commented on docs/080-breaking-changes.rst
> +  Burada, ``T`` ve ``S`` tipleri ve ``x`` de ``S`` tipindeki herhangi bir arbitrary değişken olmak üzere, ``T(x)`` açık dönüşümünü belirtmek için ``T(S)`` notasyonunu kullanalım. Hem genişliği (8 bit
```suggestion
  Burada, ``T`` ve ``S`` tipleri ve ``x`` de ``S`` tipindeki herhangi bir rasgele değişken olmak üzere, ``T(x)`` açık dönüşümünü belirtmek için ``T(S)`` notasyonunu kullanalım. Hem genişliği (8 bitten 16 bite) hem de işareti (işaretli tamsayıdan işaretsiz tamsayıya) değiştirdiği için bu tür bir izin verilmeyen dönüştürmeye örnek olarak ``uint16(int8)`` verilebilir. Dönüştürmeyi yapmak için bir ara türden geçmek gerekir. Önceki örnekte, bu ``uint16(uint8(int8))`` veya ``uint16(int16(int8))`` olacaktır. Dönüştürmenin iki yolunun farklı sonuçlar üreteceğini unutmayın, örneğin ``-1`` için. Aşağıda, bu kural tarafından izin verilmeyen bazı dönüşüm örnekleri verilmiştir.
```

2022-09-08 14:54 UTC, sevvalmutlu commented on docs/080-breaking-changes.rst
> +  Bu değişiklik, derleyicinin bu adreslerin ödenebilir olup olmadığını belirleyememesi nedeniyle yapılmıştır, bu nedenle artık bu gereksinimi görünür kılmak için açık bir dönüşüm gerektirmektedir. Tr
```suggestion
  Bu değişiklik, derleyicinin bu adreslerin ödenebilir olup olmadığını belirleyememesi nedeniyle yapılmıştır, bu nedenle artık bu gereksinimi görünür kılmak için açık bir dönüşüm gerektirmektedir. 
```

2022-09-08 14:54 UTC, sevvalmutlu commented on docs/080-breaking-changes.rst
> +- Aritmetiği paketlemeye güveniyorsanız, her işlemi ``unchecked { ... }``.
```suggestion
- Aritmetik paketlemeye güveniyorsanız, her işlemi ``unchecked { ... }``.
```

2022-09-08 18:00 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +  Bu, üs alma operatörünü ayrıştırmanın yaygın yoludur.
Buradaki üs, üslü sayılardaki üs

2022-09-09 18:08 UTC, ilketh requested changes

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +Semantiğin Sessiz Değişimleri
```suggestion
Semantikte Sessiz Değişiklikler
```
Sessiz Semantik Değişiklikleri de olabilir

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  Taşma kontrolleri çok yaygındır, bu nedenle gaz maliyetlerinde hafif bir artışa neden olsa bile kodun okunabilirliğini artırmak için bunları varsayılan hale getirdik.
```suggestion
  Taşma kontrolleri çok yaygındır, bu nedenle gaz maliyetlerinde hafif bir artışa neden olsa bile kodun okunabilirliğini artırmak için bunları varsayılan hale getirdik.
```
overflow ve underflow için 'yukarı yönlü taşma' ve 'aşağı yönlü taşma' önerim olacak. bunu uygulamasanız dahi bu cümlede overflow kullanıldığından yalnızca taşma değil 'üstten taşma' veya öneriyi kabul ederseniz 'yukarı yönlü taşma' diye güncellememiz doğru olacaktır.

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Başarısız iddialar ve sıfıra bölme veya aritmetik taşma gibi diğer dahili kontroller geçersiz işlem kodunu değil, bunun yerine geri döndürme işlem kodunu kullanır. Daha spesifik olarak, ``Panic(uin
```suggestion
* Başarısız iddialar ve sıfıra bölme veya aritmetik üstten taşma gibi diğer dahili kontroller geçersiz işlem kodunu değil, bunun yerine geri döndürme işlem kodunu kullanır. Daha spesifik olarak, ``Panic(uint256)`` fonksiyon çağrısına eşit hata verilerini, koşullara özgü bir hata koduyla kullanacaklardır.
```
Yine overflow'u seçtiğiniz terim doğrultusunda kullanmalıyız.

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Depolama alanındaki uzunluğu yanlış kodlanmış bir bayt dizisine erişilirse paniğe neden olunur.
```suggestion
* Depolama alanında uzunluğu yanlış kodlanmış bir bayt dizisine erişilmesi paniğe neden olunur.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Dizi uzunluğu ifadelerinde sabitler kullanılırsa, Solidity'nin önceki sürümleri değerlendirme ağacının(evaluation tree) tüm dallarında(branch) rastgele arbitrary kullanırdı. Artık, sabit değişkenle
```suggestion
* Dizi uzunluğu ifadelerinde sabitler kullanılması halinde Solidity'nin önceki sürümleri, değerlendirme ağacının (evaluation tree) tüm dallarında (branch) rastgele (arbitrary) kesinlik kullanırdı. Artık, sabit değişkenler ara ifadeler olarak kullanıldığında, değerleri, çalışma zamanı ifadelerinde kullanıldıklarında olduğu gibi uygun şekilde yuvarlanacaktır.
```
precision referans sözlüklerde duyarlık olarak geçtiği için bu şekilde ekledim ancak standart kullanım farklıysa değiştirebilirsiniz. 'precision' çevrilmeden atlanmış. 'kesinlik' olarak da geçiyor bu arada.

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Değişmezlerin açık dönüşümleri ile ilgili yeni kısıtlamalar vardır. Aşağıdaki durumlarda önceki davranış muhtemelen belirsizdi:
Alt cümlelerde literals 'literaller' olarak devam ediyor. Burda da 'değişmez' değil 'literal' uygulayalım veya alttakileri değiştirelim?

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  4. Değişmezler ve ``address`` türü arasındaki açık dönüşümler (örneğin ``address(literal)``) ``address payable`` yerine ``address`` türüne sahiptir. Açık bir dönüşüm, yani ``payable(literal)`` kull
```suggestion
  4. Değişmezler ve ``address`` türü arasındaki açık dönüşümler (örneğin ``address(literal)``), ``address payable`` yerine ``address`` türüne sahiptir. Açık bir dönüşüm, yani ``payable(literal)`` kullanılarak payable bir adres türü elde edilebilir.
```
Değişmez mi literal mi?
Bir de 'payable' kod olarak yer almadığında çevrilmeli diye düşünüyorum?

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  Burada, ``T`` ve ``S`` tipleri ve ``x`` de ``S`` tipindeki herhangi bir arbitrary değişken olmak üzere, ``T(x)`` açık dönüşümünü belirtmek için ``T(S)`` notasyonunu kullanalım. Hem genişliği (8 bit
```suggestion
  Burada, ``T`` ve ``S`` tipler, ``x`` ise ``S`` tipindeki herhangi bir rastgele değişken olmak üzere, ``T(x)`` açık dönüşümünü belirtmek için ``T(S)`` notasyonunu kullanalım. Hem genişliği (8 bitten 16 bite) hem de işareti (işaretli tamsayıdan işaretsiz tamsayıya) değiştiren ``uint16(int8)``, bu tür izin verilmeyen bir dönüşüme örnek teşkil edebilir. Dönüşümü gerçekleştirmek için bir ara türden geçmek gerekir. Önceki örnekte bu, ``uint16(uint8(int8))`` veya ``uint16(int16(int8))`` olacaktır. İki dönüşümün, örneğin ``-1`` için farklı sonuçlar oluşturacağını unutmayın. Aşağıda, bu kural gereği izin verilmeyen bazı dönüşüm örnekleri verilmiştir.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  - ``payable(uint160)``, ``payable(bytes20)`` ve ``payable(integer-literal)``: hem tür kategorisi hem de durum değiştirilebilirliği dönüştürülüyor. Bunu sırasıyla ``payable(address(uint160))``, ``pa
```suggestion
  - ``payable(uint160)``, ``payable(bytes20)`` ve ``payable(integer-literal)``: hem tür kategorisini hem de durum değiştirilebilirliğini dönüştürüyor. Bunu sırasıyla ``payable(address(uint160))``, ``payable(address(bytes20))`` ve ``payable(address(integer-literal))`` ile değiştirin. ``payable(0)``ın geçerli olduğunu ve kuralın bir istisnası olduğunu unutmayın.
```
alt ve üstte 'dönüştürüyor' demişsiniz.

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  - ``Contract(uint)``: hem tür kategorisini hem de genişliği dönüştürür. Bunu ``Contract(address(uint160(uint)))`` ile değiştirin.
```suggestion
  - ``Contract(uint)``: hem tür kategorisini hem de genişliği dönüştürüyor. Bunu ``Contract(address(uint160(uint)))`` ile değiştirin.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  Belirsizliği önlemek için bu dönüşümlere izin verilmemiştir. Örneğin, ``uint16 x = uint16(int8(-1))`` ifadesinde, ``x`` değeri önce işaret veya genişlik dönüşümünün uygulanıp uygulanmadığına bağlı
```suggestion
  Belirsizliği önlemek için bu dönüşümlere izin verilmemiştir. Örneğin, ``uint16 x = uint16(int8(-1))`` ifadesinde, ``x`` değeri, işaret ve genişlik dönüşümünden hangisinin önce uygulandığına bağlı olacaktır.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Public fonksiyonlar ve event`ler haricinde ``this``, ``super`` ve ``_`` isimli tanımlamalara izin verilmez. İstisna, bu tür fonksiyon isimlerine izin veren Solidity dışındaki dillerde uygulanan söz
```suggestion
* Public fonksiyonlar ve event`ler haricinde ``this``, ``super`` ve ``_`` isimli açıklamalara izin verilmez. İstisna, bu tür fonksiyon isimlerine izin veren Solidity dışındaki dillerde uygulanan sözleşmelerin arayüzlerini açıklamayı mümkün kılmaktır.
```
Public 'herkese açık'?

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Koddaki ``\b``, ``\f`` ve ``\v`` kaçış dizileri için destek kaldırıldı. Bunlar hala onaltılık kaçış dizileri aracılığıyla eklenebilir, örneğin sırasıyla ``\x08``, ``\x0c`` ve ``\x0b``.
```suggestion
* Koddaki ``\b``, ``\f`` ve ``\v`` kaçış dizileri için destek kaldırılmıştır. Bunlar, onaltılık kaçış dizileri aracılığıyla eklenmeye devam edebilir; örneğin, sırasıyla ``\x08``, ``\x0c`` ve ``\x0b``.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Global değişkenler ``tx.origin`` ve ``msg.sender``, ``address payable`` yerine ``address`` tipine sahiptir. Bunları açık bir dönüşüm kullanarak ``address payable`` türüne dönüştürebilirsiniz, yani
```suggestion
* Global değişkenler ``tx.origin`` ve ``msg.sender``, ``address payable`` yerine ``address`` tipine sahiptir. Bunlar, açık bir dönüşüm kullanılarak ``address payable`` türüne, yani ``payable(tx.origin)`` veya ``payable(msg.sender)``a dönüştürülebilir.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* ``address`` türüne açık dönüştürme her zaman ödenebilir olmayan bir ``address`` türü döndürür. Özellikle, aşağıdaki açık dönüşümler ``address payable`` yerine ``address`` türüne sahiptir:
```suggestion
* ``address`` türüne açık dönüşüm, her zaman, ödenebilir olmayan bir ``address`` türü döndürür. Özellikle, aşağıdaki açık dönüşümler ``address payable`` yerine ``address`` türüne sahiptir:
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  - ``address(u)`` burada ``u`` ``uint160`` türünde bir değişkendir. Biri ``u`` türünü iki açık dönüşüm kullanarak ``address payable`` türüne dönüştürebilir, yani ``payable(address(u))``.
```suggestion
  - ``u``nun ``uint160`` türü bir değişken olduğu ``address(u)``. ``u``, iki açık dönüşüm kullanılarak ``payable(address(u))`` şeklinde ``address payable`` türüne dönüştürebilir.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  - ``address(b)`` burada ``b`` ``bytes20`` tipinde bir değişkendir. Biri ``b`` türünü iki açık dönüşüm kullanarak `` address payable`` türüne dönüştürebilir, yani ``payable(address(b))``.
```suggestion
  - ``b``nin ``bytes20`` türü bir değişken olduğu ``address(b)``. ``b``, iki açık dönüşüm kullanılarak ``payable(address(b))`` şeklinde `` address payable`` türüne dönüştürebilir.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  - ``address(c)``, burada ``c`` bir sözleşmedir. Önceden, bu dönüşümün dönüş türü, sözleşmenin Ether alıp alamayacağına bağlıydı (bir receive fonksiyonuna veya bir payable fallback fonksiyonuna sahi
```suggestion
  - ``c``nin bir sözleşme olduğu ``address(c)``. Önceden, bu dönüşümün dönüş türü, sözleşmenin Ether alıp alamayacağına (bir receive fonksiyonuna veya bir payable fallback fonksiyonuna sahip olarak) bağlıydı. ``payable(c)`` dönüşümü ``address payable`` türüne sahiptir ve yalnızca ``c`` sözleşmesi Ether alabildiğinde bu dönüşüme izin verilir. Genel olarak ``c``, şu açık dönüşüm kullanılarak her zaman ``address payable`` türüne dönüştürülebilir: ``payable(address(c))``. ``address(this)`` türünün ``address(c)`` ile aynı kategoriye girdiğini ve aynı kuralların onun için de geçerli olduğunu unutmayın.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +  Yerine "kompakt AST" (``--ast-compact--json`` resp. ``AST``) kullanın.
buradaki resp. nedir acaba?

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +- Aritmetiği paketlemeye güveniyorsanız, her işlemi ``unchecked { ... }``.
```suggestion
- Aritmetik paketlemeye güveniyorsanız, her işlemi ``unchecked { ... }`` ile çevreleyin.
```
sarın, çevirin, ?

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +- Eski ABI kodlayıcı ile kalmak istiyorsanız ``pragma abicoder v1;`` ekleyin.
```suggestion
- Eski ABI kodlayıcı ile devam etmek istiyorsanız ``pragma abicoder v1;`` ekleyin.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +- Gerekirse ara açık tip dönüşümleri ekleyin.
```suggestion
- Gerekirse ara açık tip dönüşümler ekleyin.
```

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +- ``msg.sender.transfer(x)`` öğesini ``payable(msg.sender).transfer(x)`` olarak değiştirin veya ``address payable`` türünde bir saklı değişken kullanın.
```suggestion
- ``msg.sender.transfer(x)`` öğesini ``payable(msg.sender).transfer(x)`` olarak değiştirin veya ``address payable`` türü saklanmış bir değişken kullanın.
```
saklı, 'gizli' (hidden) ile karıştırılır mı diye değiştirdim. 'depolanmış' da denebilir

2022-09-09 18:08 UTC, ilketh commented on docs/080-breaking-changes.rst
> +* Aritmetik işlemler alttan taşma ve üstten taşma durumunda geri döner. Önceki paketleme davranışını kullanmak için ``unchecked { ... }`` kullanarak önceki paketleme davranışını kullanabilirsiniz.
```suggestion
* Aritmetik işlemler alttan taşma ve üstten taşma durumunda geri döner. Önceki paketleme davranışını kullanmak için ``unchecked { ... }`` öğesini kullanabilirsiniz.

2022-09-18 11:35 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +* Değişmezlerin açık dönüşümleri ile ilgili yeni kısıtlamalar vardır. Aşağıdaki durumlarda önceki davranış muhtemelen belirsizdi:
```suggestion
* Literallerin açık dönüşümleri ile ilgili yeni kısıtlamalar vardır. Aşağıdaki durumlarda önceki davranış muhtemelen belirsizdi:
```

2022-09-18 11:37 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +  4. Değişmezler ve ``address`` türü arasındaki açık dönüşümler (örneğin ``address(literal)``) ``address payable`` yerine ``address`` türüne sahiptir. Açık bir dönüşüm, yani ``payable(literal)`` kull
```suggestion
  4. Literaller ve ``address`` türü arasındaki açık dönüşümler (örneğin ``address(literal)``) ``address payable`` yerine ``address`` türüne sahiptir. Açık bir dönüşüm, yani ``payable(literal)`` kullanılarak payable(ödenebilir) bir adres türü elde edilebilir.
```

2022-09-18 11:40 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +* Public fonksiyonlar ve event`ler haricinde ``this``, ``super`` ve ``_`` isimli tanımlamalara izin verilmez. İstisna, bu tür fonksiyon isimlerine izin veren Solidity dışındaki dillerde uygulanan söz
Syntax'ta bulunan bir terim olduğu için çevirilmemesi daha doğru

2022-09-18 11:42 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +  Yerine "kompakt AST" (``--ast-compact--json`` resp. ``AST``) kullanın.
sırasıyla

2022-09-18 11:43 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +  Yerine "kompakt AST" (``--ast-compact--json`` resp. ``AST``) kullanın.
```suggestion
  Yerine "kompakt AST" (``--ast-compact--json`` sırasıyla ``AST``) kullanın.
```

2022-09-23 11:36 UTC, AliErcanOzgokce commented on docs/080-breaking-changes.rst
> +  Taşma kontrolleri çok yaygındır, bu nedenle gaz maliyetlerinde hafif bir artışa neden olsa bile kodun okunabilirliğini artırmak için bunları varsayılan hale getirdik.
```suggestion
  Üstten taşma kontrolleri çok yaygındır, bu nedenle gaz maliyetlerinde hafif bir artışa neden olsa bile kodun okunabilirliğini artırmak için bunları varsayılan hale getirdik.
```

2022-09-23 11:36 UTC, merged