Ref: #76 / 070 Breaking Changes Çevirisi
solidity-docs/tr-turkish pull request #77
Opened 2022-08-27 13:53 UTC by AliErcanOzgokce

## Referans Alınan Issue
ref: #76
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 75
- satır: 91-99

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-09-08 14:23 UTC, sevvalmutlu requested changes

2022-09-08 14:23 UTC, sevvalmutlu commented on docs/070-breaking-changes.rst
> +Fonksiyonlar ve Events
```suggestion
Fonksiyonlar ve 'Events' kullanımı için farklı alternatiflerin kullanıması gerektiğini düşünüyorum. Fonksyionlar ve Etkinlikler şeklinde olabilir. Event kalması gerekiyorsa Events yerine Event'ler olması daha makul

```

2022-09-08 14:23 UTC, sevvalmutlu commented on docs/070-breaking-changes.rst
> +* ``using A for B`` yalnızca içinde bahsedildiği sözleşmeyi etkiler. Önceden, etki kalıtsaldı. Şimdi, özelliği kullanan tüm türetilmiş sözleşmelerde ``using`` ifadesini tekrarlamanız gerekir.
```suggestion
* ``using A for B`` yalnızca içinde bahsedildiği sözleşmeyi etkiler. Önceden, etki kalıtsaldı. Şimdi, özelliği kullanan tüm türetilmiş sözleşmelerde ``using`` ifadesini tekrarlamanız gerekiyor.
```

2022-09-08 14:23 UTC, sevvalmutlu commented on docs/070-breaking-changes.rst
>  Declarations
```suggestion
Bildiriler
```

2022-09-08 14:23 UTC, sevvalmutlu commented on docs/070-breaking-changes.rst
> +Sözdizimindeki Değişiklikler
```suggestion
Söz dizimindeki Değişiklikler
```

2022-09-13 15:22 UTC, AliErcanOzgokce commented on docs/070-breaking-changes.rst
> +Fonksiyonlar ve Events
```suggestion
Fonksiyonlar ve Event'ler
```

2022-09-13 15:22 UTC, merged