Ref: #68 / Common Patterns Çevirisi
solidity-docs/tr-turkish pull request #89
Opened 2022-08-29 13:59 UTC by ilketh

## Referans Alınan Issue
ref: #68 
  
## Gözden Geçirilmesini İstediğim Satırlar
- satır: 166
- satır: 224

## Kavram Dizinine Eklenmesini İstediğim Kavramlar (Opsiyonel)

## Ek Açıklamalar (Opsiyonel)
Pattern, "model", "desen" veya "örüntü" olarak geçiyor. Bizim çevirilerimizde model ve desen kullanımıyla karşılaştım. https://fravoll.github.io/solidity-patterns/ adresinde belirtilenlere göre patterns ile sadece tasarım değil davranış, güvenlik, yükseltilebirlik ve ekonomi pattern'ları kastediliyor. Bu durumda en uygun kullanımın "örüntü" olacağını düşünüyorum. Ancak bu kararla ilgili hemfikir olmadan, önceki kullanımlarla tutarsızlık oluşmaması adına "model" kullandım.

Satır 224'ün bir komut olup olmadığından emin olamadım. Komut sayarak emir kipi kullandım ama doğru yorumlamamış olabilirim.

## Kontrol Listesi
- [X] Çeviri için son kontrolleri yaptım.
- [X] Gerekli review isteklerini gönderdim.
- [ ] Çevirim tamamlandı, paylaşıma hazır.

2022-08-30 20:10 UTC, sevvalmutlu commented
pattern için formasyon kelimesini de çok sık kullanıyoruz biz başka yerlerdeki çevirilerde tartışmaya açık tabi yine de yaklaşım çok güzel

2022-08-30 22:10 UTC, sevvalmutlu requested changes

2022-08-30 22:10 UTC, sevvalmutlu commented on docs/common-patterns.rst
> +modelini kullanmaktır. Bir etki sonucunda, en sezgisel Ether
```suggestion
modelini kullanmaktır. Bir etki sonucunda, anlaşılması en kolay Ether
```

2022-09-10 11:12 UTC, cdemircioglu commented on docs/common-patterns.rst
> +            // Re-entrancy saldırılarını önlemek için gönderim
Tekrar girme, "re-entrancy", saldirilarini....

2022-09-10 11:32 UTC, cdemircioglu commented on docs/common-patterns.rst
> +            // Re-entrancy saldırılarını önlemek için gönderim
```suggestion
            // Re-entrancy saldırılarını önlemek için gönderim
```Tekrar girme, re-entrancy, saldırılarını önlemek için gönderim

2022-09-10 11:32 UTC, cdemircioglu commented on docs/common-patterns.rst
> +            // Re-entrancy saldırılarını önlemek için gönderim
```suggestion
            // Tekrar girme, re-entrancy, saldırılarını önlemek için gönderim
```

2022-09-10 11:34 UTC, cdemircioglu commented on docs/common-patterns.rst
> +Bu, daha sezgisel olan gönderme modelinin zıttıdır:
```suggestion
Akla daha yatkin olan gönderme modeli asagidaki gibidir ama guvenlk acigi icerir:
```

2022-09-10 11:37 UTC, cdemircioglu commented on docs/common-patterns.rst
> +dolayısıyla ``becomeRichest`` fonksiyonu da başarısız olur ve sözleşme sonsuza kadar sıkışık kalır.
```suggestion
dolayısıyla ``becomeRichest`` fonksiyonu da başarısız olur ve sözleşme sonsuza kadar kitli / takili kalır.
```

2022-09-10 11:40 UTC, AliErcanOzgokce commented on docs/common-patterns.rst
> +dolayısıyla ``becomeRichest`` fonksiyonu da başarısız olur ve sözleşme sonsuza kadar sıkışık kalır.
kilitli ?

2022-09-10 12:00 UTC, cdemircioglu commented on docs/common-patterns.rst
> +Sözleşme durumunuza okuma erişimini **diğer sözleşmeler**
```suggestion
Sözleşme durum degiskenlerinin okuma erişimini **diğer sözleşmeler**
```

2022-09-10 12:07 UTC, cdemircioglu commented on docs/common-patterns.rst
> +                // Sürüm 0.4.0 öncesinde bu, Solidity
```suggestion
                // Solidity sürüm 0.4.0 öncesinde bu, 
```

2022-09-10 12:07 UTC, cdemircioglu commented on docs/common-patterns.rst
> +                // için iade yapmıyordu.
```suggestion
                // iade yapmıyordu.
```

2022-09-10 12:15 UTC, cdemircioglu requested changes
Bir kac noktada degisiklik onerdim.

2022-09-10 12:17 UTC, cdemircioglu commented on docs/common-patterns.rst
> +dolayısıyla ``becomeRichest`` fonksiyonu da başarısız olur ve sözleşme sonsuza kadar sıkışık kalır.
kontrattaki coinler ulasilamaz hale gelir. oyuzden kilitli dedim.

2022-09-13 15:07 UTC, merged